/***********************************************
* FUNCTION: [DBO].[UDF_VALIDATE_EMAIL]
* CREATION DATE: August/23/2018
* MODIFICATION DATE: October/08/2018 
* AUTHOR: FERNANDO CASAS OSORIO
* DESCRIPTION: USER-DEFINED FUNCTION TO VALIDATE AN EMAIL ADDRESSES
* VERSION 2.0 
* FIXED: FULL ALPHABET, LOCAL-PART BETWEEN QUOTES, SEPARATE VALIDATION OF LOCAL-PART AND DOMAIN 
*/
CREATE FUNCTION [DBO].[UDF_VALIDATE_EMAIL] (@EMAIL AS VARCHAR(255), @RECURRENT AS BIT = 0)
--@EMAIL is the email address to validate
RETURNS BIT
--The @RESULT is 1 when @EMAIL is valid and @RESULT = 0 when @EMAIL is invalid
AS
	BEGIN
	--VARIABLES
	DECLARE
	@ALPHABET	AS VARCHAR(255)	= NULL, -- Alphabet for valid characters in a email address
	@LENGTH		AS INT			= NULL, -- Length of the email address
	@POSITION	AS INT          = 1,    -- Position in @EMAIL
	@RESULT		AS BIT			= 1,    -- Result of validation process
	@LOCALPART	AS VARCHAR(255)	= NULL,
	@DOMAIN		AS VARCHAR(255)	= NULL

	SET @EMAIL = LTRIM(RTRIM(@EMAIL))
	SET @LOCALPART = SUBSTRING(@EMAIL, 0,LEN(@EMAIL) - CHARINDEX('@',REVERSE(@EMAIL),0) + 1)
	SET @DOMAIN = SUBSTRING(@EMAIL, LEN(@EMAIL) - CHARINDEX('@',REVERSE(@EMAIL),0) + 2,LEN(@EMAIL)  - (LEN(@EMAIL) - CHARINDEX('@',REVERSE(@EMAIL),0))-1)

	IF @RECURRENT = 1 AND @LOCALPART = ''
		SET @EMAIL = 'a@' + @DOMAIN 

	--BASIC VALIDATION
	--NOT NULL
	--LOCAL-PART + @ + DOMAIN
	--WITHOUT SPACES
	--ONLY ONE "@"
	IF (@EMAIL IS NULL) OR (NOT @EMAIL LIKE '%_@__%.__%') OR (CHARINDEX(' ',LTRIM(RTRIM(@EMAIL))) > 0) 
		OR (SELECT (LEN(@EMAIL) - LEN(REPLACE(@EMAIL, '@', '')))) <> 1  
		BEGIN
		SET @RESULT = 0
		RETURN(@RESULT)
		END
	ELSE
		BEGIN
		IF LEN(@LOCALPART) > 64
			BEGIN
			SET @RESULT = 0
			RETURN(@RESULT)
			END

		--IF LOCAL-PART BETWEEN QUOTES, DON'T VALIDATE START AND END DOTS
		IF @RECURRENT = 1 
			BEGIN
			IF (@LOCALPART LIKE '.%')
				SET @LOCALPART = SUBSTRING(@LOCALPART, 2, LEN(@LOCALPART) -1)
			IF (@LOCALPART LIKE '%.')
				SET @LOCALPART = SUBSTRING(@LOCALPART, 1, LEN(@LOCALPART) -1)
			END

		IF (@LOCALPART LIKE '.%') OR (@LOCALPART LIKE '%.') OR (@DOMAIN LIKE '-%') OR (@DOMAIN LIKE '%-') 
			OR (@DOMAIN LIKE '%--%') OR (@DOMAIN LIKE '.%') OR (@DOMAIN LIKE '%.')
			BEGIN
			SET @RESULT = 0
			RETURN(@RESULT)
			END

		--VALIDATE LOCAL-PART BETWEEN QUOTES
		IF @LOCALPART LIKE '%"%"%'
			BEGIN
			IF (SELECT (LEN(@LOCALPART) - LEN(REPLACE(@LOCALPART, '"', '')))) % 2 <> 0
				BEGIN
				SET @RESULT = 0
				RETURN(@RESULT)
				END
			ELSE
				BEGIN
				RETURN([DBO].[UDF_VALIDATE_EMAIL](REPLACE(@LOCALPART, SUBSTRING(@LOCALPART, CHARINDEX('"',@LOCALPART), 
				CHARINDEX('"',@LOCALPART,CHARINDEX('"',@LOCALPART) + 1) - CHARINDEX('"',@LOCALPART) + 1),'') + '@' + @DOMAIN, 1))
				END
			END

		IF (@EMAIL LIKE '%..%')
			BEGIN
			SET @RESULT = 0
			RETURN(@RESULT)
			END

		-- VALIDATE LOCAL-PART CHARACTERS ONE TO ONE
		SET @LENGTH = LEN(@LOCALPART)
		SET @ALPHABET = 'abcdefghijklmnopqrstuvwxyz01234567890.!#$%&*/=?^_+-`{|}~'
 
		WHILE (@POSITION <= @LENGTH)
			BEGIN
			IF CHARINDEX(SUBSTRING(@LOCALPART, @POSITION, 1), @ALPHABET) = 0
				BEGIN
				SET @RESULT = 0
				RETURN(@RESULT)
				END
			SET @POSITION += 1
			END

		-- VALIDATE DOMAIN CHARACTERS ONE TO ONE
		SET @LENGTH = LEN(@DOMAIN)
		SET @ALPHABET = 'abcdefghijklmnopqrstuvwxyz01234567890-.'
		SET @POSITION = 1
		SET @RESULT = 1
 
		WHILE (@POSITION <= @LENGTH)
			BEGIN
			IF CHARINDEX(SUBSTRING(@DOMAIN, @POSITION, 1), @ALPHABET) = 0
				BEGIN
				SET @RESULT = 0
				RETURN(@RESULT)
				END
			SET @POSITION += 1
			END
		END
RETURN @RESULT
END